<script>
  import '../app.css';
  import { onMount } from 'svelte';
  import { base } from '$app/paths';

  let { children } = $props();
  let darkMode = $state(false);
  let lang = $state('el'); // 'el' or 'en'

  onMount(() => {
    // Check system preference
    if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      darkMode = true;
      document.documentElement.classList.add('dark');
    }
    // Check saved preference
    const saved = localStorage?.getItem?.('darkMode');
    if (saved !== null) {
      darkMode = saved === 'true';
      document.documentElement.classList.toggle('dark', darkMode);
    }
    const savedLang = localStorage?.getItem?.('lang');
    if (savedLang) lang = savedLang;
  });

  function toggleDark() {
    darkMode = !darkMode;
    document.documentElement.classList.toggle('dark', darkMode);
    try { localStorage.setItem('darkMode', String(darkMode)); } catch {}
  }

  function toggleLang() {
    lang = lang === 'el' ? 'en' : 'el';
    try { localStorage.setItem('lang', lang); } catch {}
  }
</script>

<div class="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)]">
  <!-- Header -->
  <header class="border-b border-[var(--color-border)] bg-primary-700 text-white">
    <div class="max-w-6xl mx-auto px-4 py-4">
      <div class="flex items-center justify-between">
        <a href="{base}/" class="text-xl font-bold tracking-tight">
          {lang === 'el' ? 'Ελληνικά Νέα' : 'Greek News'}
          <span class="text-primary-200 text-sm font-normal ml-2">AI Digest</span>
        </a>

        <nav class="flex items-center gap-4">
          <a href="{base}/archive" class="text-primary-200 hover:text-white text-sm">
            {lang === 'el' ? 'Αρχείο' : 'Archive'}
          </a>
          <a href="{base}/feeds" class="text-primary-200 hover:text-white text-sm">RSS</a>
          <a href="{base}/about" class="text-primary-200 hover:text-white text-sm">
            {lang === 'el' ? 'Σχετικά' : 'About'}
          </a>

          <!-- Language toggle -->
          <button onclick={toggleLang}
                  class="px-2 py-1 text-xs rounded border border-primary-400 text-primary-200 hover:text-white hover:border-white transition">
            {lang === 'el' ? 'EN' : 'EL'}
          </button>

          <!-- Dark mode toggle -->
          <button onclick={toggleDark}
                  class="p-1.5 rounded-full hover:bg-primary-600 transition"
                  aria-label="Toggle dark mode">
            {#if darkMode}
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"/>
              </svg>
            {:else}
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path d="M17.293 13.293A8 8 0 716.707 2.707a8.001 8.001 0 1010.586 10.586z"/>
              </svg>
            {/if}
          </button>
        </nav>
      </div>
    </div>
  </header>

  <!-- Main content -->
  <main class="max-w-6xl mx-auto px-4 py-6">
    {@render children()}
  </main>

  <!-- Footer -->
  <footer class="border-t border-[var(--color-border)] mt-12 py-6">
    <div class="max-w-6xl mx-auto px-4 text-center text-sm text-[var(--color-text-secondary)]">
      <p>
        {lang === 'el'
          ? 'Δημιουργήθηκε με AI. Οι περιλήψεις δεν αντικαθιστούν τα πρωτότυπα άρθρα.'
          : 'Generated by AI. Summaries do not replace original articles.'}
      </p>
      <p class="mt-1">
        <a href="{base}/feeds" class="text-primary-500 hover:underline">RSS Feeds</a>
        &middot;
        <a href="{base}/about" class="text-primary-500 hover:underline">
          {lang === 'el' ? 'Σχετικά' : 'About'}
        </a>
      </p>
    </div>
  </footer>
</div>
