<script>
  import '../app.css';
  import { onMount } from 'svelte';
  import { base } from '$app/paths';

  let { children } = $props();
  let darkMode = $state(false);
  let lang = $state('el'); // 'el' or 'en'

  onMount(() => {
    // Check system preference
    if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      darkMode = true;
      document.documentElement.classList.add('dark');
    }
    // Check saved preference
    const saved = localStorage?.getItem?.('darkMode');
    if (saved !== null) {
      darkMode = saved === 'true';
      document.documentElement.classList.toggle('dark', darkMode);
    }
    const savedLang = localStorage?.getItem?.('lang');
    if (savedLang) lang = savedLang;
  });

  function toggleDark() {
    darkMode = !darkMode;
    document.documentElement.classList.toggle('dark', darkMode);
    try { localStorage.setItem('darkMode', String(darkMode)); } catch {}
  }

  function toggleLang() {
    lang = lang === 'el' ? 'en' : 'el';
    try { localStorage.setItem('lang', lang); } catch {}
    // Notify pages so they can react without a reload
    window.dispatchEvent(new CustomEvent('langchange', { detail: lang }));
  }
</script>

<div class="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)]">
  <!-- Masthead -->
  <header class="border-b-2 border-[var(--color-ink)]">
    <div class="max-w-6xl mx-auto px-4 pt-6 pb-0 text-center">
      <p class="kicker text-[var(--color-text-secondary)]">
        {lang === 'el' ? 'Ημερησια ανασκοπηση με AI' : 'Daily AI-powered digest'}
      </p>
      <a href="{base}/" class="font-serif-news block text-4xl sm:text-5xl font-semibold tracking-tight mt-1 mb-4 hover:text-[var(--color-accent)] transition-colors">
        {lang === 'el' ? 'Ελληνικά Νέα' : 'Greek News'}
      </a>

      <div class="rule-thin flex items-center justify-between py-2 text-sm">
        <nav class="flex items-center gap-4">
          <a href="{base}/archive" class="text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] transition-colors">
            {lang === 'el' ? 'Αρχείο' : 'Archive'}
          </a>
          <a href="{base}/feeds" class="text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] transition-colors">RSS</a>
          <a href="{base}/about" class="text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] transition-colors">
            {lang === 'el' ? 'Σχετικά' : 'About'}
          </a>
        </nav>

        <div class="flex items-center gap-3">
          <!-- Language toggle -->
          <button onclick={toggleLang}
                  class="px-2 py-0.5 text-xs rounded border border-[var(--color-rule)] text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] hover:border-[var(--color-accent)] transition">
            {lang === 'el' ? 'EN' : 'EL'}
          </button>

          <!-- Dark mode toggle -->
          <button onclick={toggleDark}
                  class="p-1.5 rounded-full text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] transition"
                  aria-label="Toggle dark mode">
            {#if darkMode}
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"/>
              </svg>
            {:else}
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"/>
              </svg>
            {/if}
          </button>
        </div>
      </div>
    </div>
  </header>

  <!-- Main content -->
  <main class="max-w-6xl mx-auto px-4 py-6">
    {@render children()}
  </main>

  <!-- Footer -->
  <footer class="border-t-2 border-[var(--color-ink)] mt-12 py-6">
    <div class="max-w-6xl mx-auto px-4 text-center text-sm text-[var(--color-text-secondary)]">
      <p class="font-serif-news italic">
        {lang === 'el'
          ? 'Δημιουργήθηκε με AI. Οι περιλήψεις δεν αντικαθιστούν τα πρωτότυπα άρθρα.'
          : 'Generated by AI. Summaries do not replace original articles.'}
      </p>
      <p class="mt-1">
        <a href="{base}/feeds" class="text-[var(--color-accent)] hover:underline">RSS Feeds</a>
        &middot;
        <a href="{base}/about" class="text-[var(--color-accent)] hover:underline">
          {lang === 'el' ? 'Σχετικά' : 'About'}
        </a>
      </p>
    </div>
  </footer>
</div>
