<script>
  let lang = $state('el');
  import { onMount } from 'svelte';
  onMount(() => {
    const saved = localStorage?.getItem?.('lang');
    if (saved) lang = saved;
  });
</script>

<svelte:head>
  <title>{lang === 'el' ? 'Σχετικά' : 'About'} - Greek News AI Digest</title>
</svelte:head>

<div class="max-w-3xl">
  {#if lang === 'el'}
    <h1 class="text-3xl font-bold mb-6">Σχετικά</h1>

    <div class="prose-greek space-y-4 text-[var(--color-text)]">
      <p>
        Αυτό το project συλλέγει αυτόματα ειδήσεις από ελληνικές πηγές κάθε μέρα,
        τις αναλύει με τεχνητή νοημοσύνη (Claude Sonnet) και παράγει μια δίγλωσση
        ημερήσια ανασκόπηση στα Ελληνικά και τα Αγγλικά.
      </p>

      <h2 class="text-xl font-semibold mt-8">Πηγές</h2>
      <p>
        Κύρια πηγή: Καθημερινή (μέσω RSS και PressReader API). Προαιρετικά: τάσεις Twitter/X για Ελλάδα.
      </p>

      <h2 class="text-xl font-semibold mt-8">Πώς λειτουργεί</h2>
      <p>
        Κάθε μέρα, ένα αυτόματο pipeline:
      </p>
      <p>
        1. Συλλέγει άρθρα από τις πηγές (RSS feeds, PressReader API, Twitter)
      </p>
      <p>
        2. Αναλύει κάθε άρθρο με AI: σημαντικότητα, κατηγορία, δίγλωσση περίληψη
      </p>
      <p>
        3. Εντοπίζει τα κορυφαία θέματα της ημέρας
      </p>
      <p>
        4. Δημιουργεί εκτελεστική σύνοψη στα Ελληνικά και τα Αγγλικά
      </p>
      <p>
        5. Δημοσιεύει τα αποτελέσματα σε αυτή τη σελίδα και σε RSS feeds
      </p>

      <h2 class="text-xl font-semibold mt-8">Σημαντική σημείωση</h2>
      <p>
        Οι περιλήψεις δημιουργούνται αυτόματα από AI και μπορεί να περιέχουν ανακρίβειες.
        Ανατρέξτε πάντα στα πρωτότυπα άρθρα για πλήρη και ακριβή πληροφόρηση.
      </p>

      <h2 class="text-xl font-semibold mt-8">Τεχνολογία</h2>
      <p>
        Python + Claude Sonnet API + SvelteKit + GitHub Actions + GitHub Pages.
        Βασισμένο στο <a href="https://github.com/flyryan/ai-news-aggregator" class="text-primary-600 hover:underline">AI News Aggregator</a>.
      </p>
    </div>

  {:else}
    <h1 class="text-3xl font-bold mb-6">About</h1>

    <div class="space-y-4 text-[var(--color-text)]">
      <p>
        This project automatically collects news from Greek sources daily,
        analyzes them using AI (Claude Sonnet), and produces a bilingual
        daily digest in Greek and English.
      </p>

      <h2 class="text-xl font-semibold mt-8">Sources</h2>
      <p>
        Primary: Kathimerini (via RSS and PressReader API). Optional: Twitter/X trends for Greece.
      </p>

      <h2 class="text-xl font-semibold mt-8">How it works</h2>
      <p>
        Every day, an automated pipeline: 1) Collects articles from sources (RSS feeds, PressReader API, Twitter),
        2) Analyzes each article with AI for importance, category, and bilingual summary,
        3) Detects the day's top themes, 4) Generates an executive summary in Greek and English,
        5) Publishes results to this site and RSS feeds.
      </p>

      <h2 class="text-xl font-semibold mt-8">Important note</h2>
      <p>
        Summaries are automatically generated by AI and may contain inaccuracies.
        Always refer to original articles for complete and accurate information.
      </p>

      <h2 class="text-xl font-semibold mt-8">Technology</h2>
      <p>
        Python + Claude Sonnet API + SvelteKit + GitHub Actions + GitHub Pages.
        Based on <a href="https://github.com/flyryan/ai-news-aggregator" class="text-primary-600 hover:underline">AI News Aggregator</a>.
      </p>
    </div>
  {/if}
</div>
