#!/usr/bin/env python3
"""Build 2026-06-12 per-category JSON + summary.json from scraped articles.
Analysis (summary/importance/tags/sentiment) written from the article content.
Reads merged raw from $RAW (workdir collected_raw.json), writes to
frontend/static/data/2026-06-12/.
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

DATE = "2026-06-12"
RAW = os.environ["RAW"]
REPO = Path("/sessions/vibrant-adoring-wozniak/mnt/greek-news-aggregator")
OUT = REPO / "frontend" / "static" / "data" / DATE
OUT.mkdir(parents=True, exist_ok=True)

# id -> i(mportance), el/en summary, tel/ten tags, s(entiment)
A = {
 # ===== POLITICS =====
 "9c5f741445a9": {"i":62,"el":"Τα νέα μέλη της κυβέρνησης ορκίστηκαν στο Προεδρικό Μέγαρο μετά τον μίνι-ανασχηματισμό. Αναπληρωτής υπουργός Μεταφορών αναλαμβάνει ο Γ. Κώτσηρας, υφυπουργός Φορολογικής Πολιτικής ο Δ. Μαρκόπουλος και υφυπουργός Εξωτερικών για ευρωπαϊκές υποθέσεις ο Τ. Χατζηβασιλείου.","en":"New cabinet members were sworn in at the Presidential Mansion following the mini-reshuffle. Giorgos Kotsiras becomes alternate transport minister, Dimitris Markopoulos deputy minister for tax policy, and Tasos Hatzivasileiou deputy foreign minister for European affairs.","tel":["ανασχηματισμός","κυβέρνηση","ορκωμοσία","Μητσοτάκης"],"ten":["reshuffle","cabinet","swearing-in","Mitsotakis"],"s":"neutral"},
 "a37d14258390": {"i":66,"el":"Στήλη Θεωρείο για τη στρατηγική του Μαξίμου να αντιμετωπίσει το σκάνδαλο των πολεοδομιών ως «ευκαιρία» ενόψει εκλογών, παρουσιάζοντας τη ΝΔ ως δύναμη που χτυπά το «βαθύ κράτος». Ο Μητσοτάκης άφησε και αιχμή για τον Κ. Σημίτη.","en":"A Theoreio column on Maximos Mansion's strategy of treating the urban-planning scandal as an 'opportunity' ahead of elections, casting New Democracy as the force confronting the 'deep state'. Mitsotakis also took a swipe at the late Costas Simitis.","tel":["Θεωρείο","βαθύ κράτος","πολεοδομίες","ΝΔ"],"ten":["Theoreio","deep state","urban planning","New Democracy"],"s":"neutral"},
 "3fc99e2ed0e9": {"i":58,"el":"Στήλη «Εντός και Εκτός» με θέματα άμυνας: ο Ν. Δένδιας υποδέχθηκε τις πρώτες εθελόντριες οπλίτες, ενώ για πρώτη φορά γυναίκα αξιωματικός ανέλαβε εκπρόσωπος Τύπου του ΓΕΕΘΑ. Αναφορά και στην ανάληψη της αντιπροσωπείας της ΕΕ στη Λιβύη από Έλληνα διπλωμάτη.","en":"The 'Within and Beyond' column on defense matters: Nikos Dendias welcomed the armed forces' first female volunteer soldiers, and a woman officer became GEETHA spokesperson for the first time. It also notes a Greek diplomat heading the EU delegation in Libya.","tel":["Δένδιας","Ένοπλες Δυνάμεις","γυναίκες","ΕΕ Λιβύη"],"ten":["Dendias","armed forces","women","EU Libya"],"s":"neutral"},
 "2f9ec70245d3": {"i":70,"el":"Ο ΣΥΡΙΖΑ κινείται «σε τεντωμένο σχοινί» μετά την απόφαση συμπόρευσης με τον Αλ. Τσίπρα, με στελέχη ακόμη και της πλειοψηφίας να ζητούν πιο «καθαρή γραμμή». Ο Π. Πολάκης έχει θέσει δεκαήμερη προθεσμία στον πρόεδρο Σ. Φάμελλο για συμφωνία.","en":"SYRIZA is 'walking a tightrope' after deciding to align with Alexis Tsipras, with even majority cadres demanding a 'cleaner line'. Pavlos Polakis has set leader Sokratis Famellos a ten-day deadline to reach a deal.","tel":["ΣΥΡΙΖΑ","Τσίπρας","Φάμελλος","Πολάκης"],"ten":["SYRIZA","Tsipras","Famellos","Polakis"],"s":"negative"},
 "84146a2845d8": {"i":64,"el":"Ο πρόεδρος του ΠΑΣΟΚ Ν. Ανδρουλάκης δεσμεύτηκε για καθολική δωρεάν μετακίνηση όλων των νέων έως 24 ετών στα ΜΜΜ Αττικής και Θεσσαλονίκης, χαρακτηρίζοντας το μέτρο κοινωνικής δικαιοσύνης για μια γενιά που δυσκολεύεται.","en":"PASOK leader Nikos Androulakis pledged universal free public transport for all young people up to age 24 in Attica and Thessaloniki, calling it a measure of social justice for a struggling generation.","tel":["Ανδρουλάκης","ΠΑΣΟΚ","δωρεάν μετακίνηση","νέοι"],"ten":["Androulakis","PASOK","free transit","youth"],"s":"positive"},
 "9d930d99de1b": {"i":63,"el":"Κόντρα Τσίπρα-Μητσοτάκη με αφορμή τη μεταφορά περί «διπλώματος οδήγησης». Ο Τσίπρας απάντησε ότι «το δίπλωμα το χάνεις όταν παραβιάζεις κανόνες, όχι όταν χάνεις εκλογές», κατηγορώντας τον πρωθυπουργό ότι έκανε τη χώρα «μόνιμο πελάτη της Ευρωπαϊκής Εισαγγελίας».","en":"A clash between Tsipras and Mitsotakis over a 'driving licence' metaphor. Tsipras retorted that 'you lose your licence for breaking rules, not for losing elections,' accusing the PM of making Greece a 'permanent client of the European Public Prosecutor'.","tel":["Τσίπρας","Μητσοτάκης","αντιπαράθεση","εκλογές"],"ten":["Tsipras","Mitsotakis","feud","elections"],"s":"negative"},
 "ba47aa375880": {"i":68,"el":"Ο πρωθυπουργός Κ. Μητσοτάκης δήλωσε στον ΑΝΤ1 ότι οι εκλογές θα γίνουν την άνοιξη του 2027, σε χαλαρό ύφος σχολιάζοντας και διακοπές και Μουντιάλ. Η αναφορά στο χρονοδιάγραμμα αποτελεί την πολιτικά σημαντικότερη είδηση.","en":"PM Mitsotakis told ANT1 that elections will be held in spring 2027, speaking in a relaxed tone that also touched on holidays and the World Cup. The timing signal is the politically significant takeaway.","tel":["Μητσοτάκης","εκλογές 2027","χρονοδιάγραμμα"],"ten":["Mitsotakis","2027 elections","timeline"],"s":"neutral"},
 "b55f79cc7e64": {"i":60,"el":"Ο πρόεδρος του Eurogroup και υπουργός Εθνικής Οικονομίας Κ. Πιερρακάκης φιλοξένησε τον πρώην πρόεδρο της Κομισιόν Ζ.-Κλ. Γιούνκερ στο άτυπο δείπνο των ΥΠΟΙΚ της Ευρωζώνης στο Λουξεμβούργο, σε κλίμα αμοιβαίας εκτίμησης.","en":"Eurogroup president and national economy minister Kyriakos Pierrakakis hosted former European Commission chief Jean-Claude Juncker at the eurozone finance ministers' informal dinner in Luxembourg, in a warm atmosphere.","tel":["Πιερρακάκης","Eurogroup","Γιούνκερ","Ευρωζώνη"],"ten":["Pierrakakis","Eurogroup","Juncker","eurozone"],"s":"positive"},
 "7faa9ecee5f0": {"i":72,"el":"Υπεγράφη στο Χιούστον η διακήρυξη ίδρυσης του East Med Energy Center (EMEC) στο πλαίσιο του σχήματος 3+1 (Ελλάδα, Κύπρος, Ισραήλ, ΗΠΑ). Ο υπουργός Ενέργειας Στ. Παπασταύρου τόνισε ότι η ενέργεια δεν πρέπει να εργαλειοποιείται.","en":"The declaration founding the East Med Energy Center (EMEC) was signed in Houston under the 3+1 scheme (Greece, Cyprus, Israel, US). Energy minister Stavros Papastavrou stressed that energy must not be weaponized.","tel":["EMEC","3+1","ενέργεια","Παπασταύρου"],"ten":["EMEC","3+1","energy","Papastavrou"],"s":"positive"},
 "3d9253aaee43": {"i":74,"el":"Το Μαξίμου αποκρούει τις κατηγορίες της αντιπολίτευσης περί «γαλάζιου» σκανδάλου στις πολεοδομίες μετά τις παραιτήσεις των γεν. γραμματέων Ε. Μπακογιάννη και Γ. Διδασκάλου, επιμένοντας ότι έγιναν για προσωπικούς λόγους.","en":"Maximos Mansion is rebutting opposition accusations of a 'New Democracy' urban-planning scandal after the resignations of general secretaries Efthymios Bakoyannis and Giorgos Didaskalou, insisting they left for personal reasons.","tel":["πολεοδομίες","Μπακογιάννης","παραιτήσεις","διαφθορά"],"ten":["urban planning","Bakoyannis","resignations","corruption"],"s":"negative"},
 "d1186bdfa7a6": {"i":61,"el":"Ο βουλευτής της ΝΔ Μ. Βορίδης εξελέγη πρόεδρος της Επιτροπής Αναθεώρησης του Συντάγματος, με αντιπρόεδρο την Ε. Λιακούλη (ΠΑΣΟΚ) και γραμματέα τον Θ. Ξανθόπουλο (ΣΥΡΙΖΑ). Η Επιτροπή θα συνεδριάζει αρχικά τρεις φορές την εβδομάδα.","en":"New Democracy MP Makis Voridis was elected chair of the Constitutional Revision Committee, with Evangelia Liakouli (PASOK) as vice-chair and Theofilos Xanthopoulos (SYRIZA) as secretary. The committee will initially meet three times a week.","tel":["Βορίδης","Σύνταγμα","αναθεώρηση","Βουλή"],"ten":["Voridis","constitution","revision","parliament"],"s":"neutral"},
 "ffb7aa0ab1d7": {"i":71,"el":"Ανάλυση για το νέο East Med Energy Center με έδρα το Baker Institute του Rice, που φιλοδοξεί να γίνει ο βασικός μηχανισμός ενεργειακής και γεωπολιτικής συνεργασίας ΗΠΑ-Ελλάδας-Κύπρου-Ισραήλ, υλοποιώντας πρόβλεψη του EastMed Act του 2019.","en":"An analysis of the new East Med Energy Center, based at Rice University's Baker Institute, which aims to become the principal mechanism for US-Greece-Cyprus-Israel energy and geopolitical cooperation, fulfilling a provision of the 2019 EastMed Act.","tel":["EMEC","Ανατ. Μεσόγειος","γεωπολιτική","ΗΠΑ"],"ten":["EMEC","East Med","geopolitics","US"],"s":"positive"},
 "364f334857d0": {"i":73,"el":"Η Τουρκία εντείνει την επίθεση κατά της Κύπρου, χαρακτηρίζοντάς την «προτεκτοράτο του Ισραήλ» και βάλλοντας κατά της αμυντικής συμφωνίας Λευκωσίας-Παρισιού. Το τουρκικό νομοσχέδιο για θαλάσσιες ζώνες ενδέχεται να μετατεθεί μετά το φθινόπωρο.","en":"Turkey is escalating its rhetoric against Cyprus, calling it an 'Israeli protectorate' and attacking the Nicosia-Paris defense pact. Turkey's maritime-zones bill may be postponed beyond the autumn.","tel":["Τουρκία","Κύπρος","Ισραήλ","θαλάσσιες ζώνες"],"ten":["Turkey","Cyprus","Israel","maritime zones"],"s":"negative"},
 "2b186cb6221d": {"i":67,"el":"Σε podcast του H.R. McMaster, ο Κ. Μητσοτάκης παρουσίασε το οικονομικό αποτύπωμα της κυβέρνησης, υποστηρίζοντας ότι η Ελλάδα έχει αφήσει πίσω την κρίση και βρίσκεται σε τροχιά σταθερής ανάπτυξης, με αναφορές σε μετανάστευση, άμυνα και ελληνοτουρκικά.","en":"On H.R. McMaster's podcast, Mitsotakis presented his government's economic record, arguing Greece has left the crisis behind and entered a path of steady growth, touching on migration, defense and Greek-Turkish relations.","tel":["Μητσοτάκης","οικονομία","ανάπτυξη","podcast"],"ten":["Mitsotakis","economy","growth","podcast"],"s":"positive"},
 # ===== ECONOMY =====
 "9a89e2656ad1": {"i":72,"el":"Διευρύνεται το χάσμα μεταξύ παλαιών και νέων συντάξεων και μεταξύ ιδιωτικού-δημόσιου τομέα, σύμφωνα με τα στοιχεία του συστήματος «Ηλιος» για τον Μάιο 2026. Μεγάλοι χαμένοι οι νέοι συνταξιούχοι του ιδιωτικού τομέα.","en":"The gap is widening between old and new pensions and between private- and public-sector retirees, per the 'Ilios' system data for May 2026. New private-sector pensioners are the biggest losers.","tel":["συντάξεις","ΕΦΚΑ","ανισότητα","Ηλιος"],"ten":["pensions","EFKA","inequality","Ilios"],"s":"negative"},
 "2d293915c4d9": {"i":66,"el":"Η κινεζική BYD φιλοδοξεί να ξεπεράσει την Toyota και να γίνει η μεγαλύτερη αυτοκινητοβιομηχανία στον κόσμο σε πέντε χρόνια, επενδύοντας πάνω από 2 δισ. ευρώ στην Ευρώπη σε υποδομές υπερταχείας φόρτισης.","en":"China's BYD aims to overtake Toyota and become the world's largest carmaker within five years, investing over €2 billion in Europe in ultra-fast charging infrastructure.","tel":["BYD","ηλεκτρικά","Toyota","Κίνα"],"ten":["BYD","EVs","Toyota","China"],"s":"neutral"},
 "701edb91d91f": {"i":58,"el":"Επιπλέον 6.000 νοικοκυριά εντάσσονται στο πρόγραμμα «Αλλάζω Σύστημα Θέρμανσης και Θερμοσίφωνα», με τη συνολική δημόσια δαπάνη να ξεπερνά τα 21,5 εκατ. ευρώ και τις εγκεκριμένες αιτήσεις τις 146.000.","en":"An additional 6,000 households are joining the 'Change Heating System and Water Heater' subsidy scheme, with total public spending exceeding €21.5 million and approved applications surpassing 146,000.","tel":["επιδότηση","θέρμανση","ΥΠΕΝ","ενέργεια"],"ten":["subsidy","heating","energy ministry","energy"],"s":"positive"},
 "f6090685e1d4": {"i":62,"el":"Σε περίοδο ανακατατάξεων εισέρχεται η αγορά διαδικτυακού τζόγου στην Ελλάδα, με νέους ξένους παρόχους, αυστηρότερο πλαίσιο και νέο φορολογικό καθεστώς. Ο όμιλος Allwyn (Stoiximan) κρατά μερίδιο που πλησιάζει το 60%.","en":"Greece's online gambling market is entering a period of upheaval, with new foreign operators, a stricter framework and a new tax regime. The Allwyn group (Stoiximan) holds nearly 60% market share.","tel":["τζόγος","Allwyn","φορολογία","ανταγωνισμός"],"ten":["gambling","Allwyn","taxation","competition"],"s":"neutral"},
 "52f936019a2f": {"i":70,"el":"Η πρώτη αύξηση επιτοκίων της ΕΚΤ μετά το 2023 αναμένεται να προσθέσει ~147 εκατ. ευρώ στα ετήσια έσοδα των ελληνικών τραπεζών, καθώς η άνοδος δεν μετακυλίεται εξίσου στις καταθέσεις, διευρύνοντας το spread δανείων-καταθέσεων.","en":"The ECB's first rate hike since 2023 is expected to add roughly €147 million to Greek banks' annual interest income, as the increase is not passed on equally to deposits, widening the loan-deposit spread.","tel":["ΕΚΤ","επιτόκια","τράπεζες","καταθέσεις"],"ten":["ECB","interest rates","banks","deposits"],"s":"neutral"},
 "7a645799ddcb": {"i":57,"el":"Η Trastor ΑΕΕΑΠ ολοκλήρωσε την αγορά τριών κτιρίων γραφείων της Εθνικής Ασφαλιστικής στο κέντρο της Αθήνας έναντι 38,6 εκατ. ευρώ, με σχέδια αναβάθμισης που θα ανεβάσουν την επένδυση στα ~55 εκατ.","en":"Real estate firm Trastor completed the €38.6 million purchase of three Ethniki Asfalistiki office buildings in central Athens, with planned upgrades raising the total investment to about €55 million.","tel":["Trastor","ακίνητα","Αθήνα","επένδυση"],"ten":["Trastor","real estate","Athens","investment"],"s":"positive"},
 "8a7950360ebe": {"i":63,"el":"Η Dimand Real Estate αναπτύσσει ακίνητα αξίας 1,7 δισ. ευρώ έως το 2029, με κορυφαία έργα την ανάπλαση του πρώην ΦΙΞ, των Κτημάτων Καμπά και της πρώην αμερικανικής βάσης στις Γούρνες Ηρακλείου. Στις 17 Ιουλίου ολοκληρώνεται το νέο Δικαστικό Μέγαρο Πειραιά.","en":"Dimand Real Estate is developing €1.7 billion of property by 2029, with flagship projects including the former FIX site, the Kampa estates and the ex-US base at Gournes, Crete. The new Piraeus courthouse is completed on July 17.","tel":["Dimand","ακίνητα","ανάπλαση","Πειραιάς"],"ten":["Dimand","real estate","redevelopment","Piraeus"],"s":"positive"},
 "e1fed72e93c5": {"i":64,"el":"Τα παγκόσμια χρέη από μικροδάνεια διπλασιάστηκαν σε 15 χρόνια, με κρίσεις αποπληρωμής σε πολλές χώρες. Το όραμα του νομπελίστα Μ. Γιουνούς για μικροχρηματοδότηση χωρίς φτώχεια έχει μετατραπεί σε φαύλο κύκλο χρέους για εκατομμύρια.","en":"Global microloan debt has doubled in 15 years, with repayment crises in many countries. Nobel laureate Muhammad Yunus's vision of poverty-free microfinance has turned into a vicious cycle of debt for millions.","tel":["μικροδάνεια","Γιουνούς","φτώχεια","χρέος"],"ten":["microfinance","Yunus","poverty","debt"],"s":"negative"},
 "417933955f74": {"i":59,"el":"Επιστροφές φόρων ύψους 191 εκατ. ευρώ παραμένουν αζήτητες σε ~130.000 δικαιούχους λόγω ελλιπών στοιχείων ή δικαιολογητικών, με κίνδυνο παραγραφής μετά από 5 χρόνια. Οι συνολικές εκκρεμείς επιστροφές φτάνουν τα 737 εκατ.","en":"€191 million in tax refunds remain unclaimed by around 130,000 beneficiaries due to incomplete data or paperwork, at risk of lapsing after five years. Total pending refunds reach €737 million.","tel":["εφορία","επιστροφές φόρου","ΑΑΔΕ","φορολογούμενοι"],"ten":["tax office","tax refunds","AADE","taxpayers"],"s":"negative"},
 "335cc6ab1c1c": {"i":56,"el":"Ανάλυση για το πώς μεταδίδονται γρήγορα οι αυξήσεις τιμών στην αγορά, με τις μικρότερες επιχειρήσεις πιο ευάλωτες. Στις ΗΠΑ πάνω από το ένα τρίτο των επιχειρήσεων αύξησε τιμές τον Μάιο, με τον πληθωρισμό στο 4,2%.","en":"An analysis of how price increases spread quickly through the market, with smaller firms more vulnerable. In the US, over a third of businesses raised prices in May, with inflation at 4.2%.","tel":["πληθωρισμός","ακρίβεια","επιχειρήσεις","τιμές"],"ten":["inflation","cost of living","businesses","prices"],"s":"negative"},
 "71a2d44c0d2c": {"i":58,"el":"Το Ελεγκτικό Συνέδριο μπλόκαρε ξανά σύμβαση των ΟΣΥ —αυτή τη φορά για την αποξήλωση του ανενεργού δικτύου τρόλεϊ— λόγω νομικών πλημμελειών, μετά και τα προβλήματα στον διαγωνισμό για τα αλκοολόμετρα.","en":"The Court of Audit again blocked an OSY transport contract — this time for dismantling the disused trolley network — over legal flaws, following earlier problems with the breathalyzer tender.","tel":["ΟΣΥ","Ελεγκτικό Συνέδριο","συγκοινωνίες","τρόλεϊ"],"ten":["OSY","Court of Audit","transit","trolleybus"],"s":"negative"},
 "e32dbe6726ae": {"i":60,"el":"Τα ληξιπρόθεσμα χρέη του Δημοσίου προς προμηθευτές παραμένουν υψηλά, στα 3,65 δισ. ευρώ στα τέλη Απριλίου, με χειρότερο κακοπληρωτή τα νοσοκομεία (1,4 δισ.). Ο υφυπουργός Θ. Πετραλιάς ζητά επιτάχυνση των πληρωμών.","en":"State arrears to suppliers remain high at €3.65 billion at end-April, with hospitals the worst payers (€1.4 billion). Deputy minister Thanos Petralias is urging faster payments.","tel":["ληξιπρόθεσμα","Δημόσιο","νοσοκομεία","προμηθευτές"],"ten":["arrears","state","hospitals","suppliers"],"s":"negative"},
 "4a4963e8bf5c": {"i":65,"el":"Άνοιξε ο δρόμος για την αύξηση μετοχικού κεφαλαίου 1 δισ. ευρώ του ΑΔΜΗΕ, μετά την έγκριση της έκτακτης γ.σ. της ΑΔΜΗΕ Συμμετοχών, που θα συμμετάσχει με 510 εκατ. Η άντληση θα γίνει με συνδυασμένη δημόσια προσφορά και ιδιωτική τοποθέτηση.","en":"The path opened for IPTO's (ADMIE) €1 billion capital increase after approval by ADMIE Holdings' extraordinary general meeting, which will contribute €510 million via a combined public offering and private placement.","tel":["ΑΔΜΗΕ","αύξηση κεφαλαίου","ενέργεια","χρηματιστήριο"],"ten":["IPTO","capital increase","energy","stock market"],"s":"positive"},
 "b69ff9e09eca": {"i":54,"el":"Σχόλιο για το νέο δίκτυο καμερών τροχαίας ύψους 44 εκατ. ευρώ, που χρηματοδοτείται από τα πρόστιμα των οδηγών — ένα παράδοξο όπου, όσο πιο επιτυχημένο είναι στη συμμόρφωση, τόσο λιγότερα έσοδα έχει.","en":"A commentary on the new €44 million traffic-camera network funded by drivers' fines — a paradox whereby the more successful it is at enforcing compliance, the less revenue it generates.","tel":["κάμερες","τροχαία","πρόστιμα","οδική ασφάλεια"],"ten":["cameras","traffic","fines","road safety"],"s":"neutral"},
 # ===== SOCIETY =====
 "5a9ebae0fca1": {"i":55,"el":"Ρεπορτάζ-πορτρέτο για ενήλικες που επιστρέφουν στο σχολείο δεκαετίες μετά, όπως η Ουρανία Κουρκούτα που εγκατέλειψε την εκπαίδευση τη δεκαετία του '60. Η «Κ» φωτίζει ιστορίες μαθητών σχολείων δεύτερης ευκαιρίας.","en":"A feature on adults returning to school decades later, such as Ourania Kourkouta who left education in the 1960s. Kathimerini profiles the stories of second-chance school students.","tel":["εκπαίδευση","δεύτερη ευκαιρία","ανθρώπινες ιστορίες"],"ten":["education","second chance","human interest"],"s":"positive"},
 "9d025c0756c2": {"i":42,"el":"Έρευνες της Αστυνομίας στο Αγρίνιο για τον τραυματισμό 35χρονου από σκάγια κυνηγετικού όπλου. Ο τραυματίας, εκτός κινδύνου, δεν έχει υποδείξει δράστη ούτε δώσει σαφείς εξηγήσεις για τις συνθήκες.","en":"Police in Agrinio are investigating the wounding of a 35-year-old by shotgun pellets. The victim, out of danger, has not named a perpetrator or clarified the circumstances.","tel":["Αγρίνιο","τραυματισμός","αστυνομία","έρευνα"],"ten":["Agrinio","shooting","police","investigation"],"s":"negative"},
 "89eeccd10d76": {"i":45,"el":"Μια 15χρονη διακομίστηκε σε κατάσταση μέθης σε νοσοκομείο της Αχαΐας. Συνελήφθη η γιαγιά της με την κατηγορία της έκθεσης ανηλίκου σε κίνδυνο.","en":"A 15-year-old was hospitalized in a drunken state in Achaea. Her grandmother was arrested on charges of child endangerment.","tel":["Αχαΐα","ανήλικη","μέθη","σύλληψη"],"ten":["Achaea","minor","intoxication","arrest"],"s":"negative"},
 "fe6db90c08bd": {"i":56,"el":"Παρατείνεται έως τις 22 Ιουνίου η προθεσμία καθαρισμού οικοπέδων, ανακοίνωσε ο υπουργός Πολιτικής Προστασίας Ε. Τουρνάς. Έχουν δηλωθεί 373.000 καθαρισμοί, εν όψει δύσκολων καιρικών συνθηκών και κινδύνου πυρκαγιών.","en":"The deadline for clearing plots of land has been extended to June 22, civil protection minister Evangelos Tournas announced. Some 373,000 clearances have been declared amid worsening weather and fire risk.","tel":["καθαρισμός οικοπέδων","πυροπροστασία","Τουρνάς","προθεσμία"],"ten":["land clearing","fire prevention","Tournas","deadline"],"s":"neutral"},
 "e74b3ac2c4bb": {"i":52,"el":"Φωτιά ξέσπασε σε δασική έκταση στην Πλάκα Κερατέας, με 62 πυροσβέστες, 20 οχήματα και 2 ελικόπτερα να επιχειρούν, μαζί με πεζοπόρα τμήματα και εθελοντές.","en":"A wildfire broke out in a forested area at Plaka Keratea, with 62 firefighters, 20 vehicles and 2 helicopters operating alongside ground crews and volunteers.","tel":["φωτιά","Κερατέα","πυροσβεστική","δάσος"],"ten":["wildfire","Keratea","fire service","forest"],"s":"negative"},
 "c6164b399f6d": {"i":68,"el":"Αποκαλυπτικοί διάλογοι «καίνε» κύκλωμα διακίνησης ναρκωτικών που στρατολογούσε ανηλίκους —ακόμη και 12 ετών— στα βόρεια προάστια, με πωλήσεις σε πάρκα, παιδικές χαρές και σχολεία.","en":"Revealing dialogues implicate a drug-trafficking ring that recruited minors — some as young as 12 — in Athens' northern suburbs, selling in parks, playgrounds and even schools.","tel":["ναρκωτικά","ανήλικοι","κύκλωμα","σχολεία"],"ten":["drugs","minors","ring","schools"],"s":"negative"},
 "090f2a952915": {"i":53,"el":"Πανεπιστημιακός καρδιολόγος στη Θεσσαλονίκη καταδικάστηκε τελεσίδικα σε φυλάκιση 28 μηνών με αναστολή για «φακελάκια» από ασθενείς για επεμβάσεις σε δημόσιο νοσοκομείο (2018-2020).","en":"A university cardiologist in Thessaloniki was given a final 28-month suspended sentence for taking bribes ('fakelaki') from patients for procedures at a public hospital (2018-2020).","tel":["φακελάκι","Θεσσαλονίκη","διαφθορά","ΕΣΥ"],"ten":["bribery","Thessaloniki","corruption","public health"],"s":"negative"},
 "6b66f7749873": {"i":54,"el":"Συνελήφθη ο 30χρονος κυβερνήτης τουριστικού σκάφους μετά τη φωτιά και βύθιση δύο σκαφών στους Παξούς, που προκάλεσε θαλάσσια ρύπανση. Οι 18 Αμερικανοί επιβάτες και τα πληρώματα αποβιβάστηκαν χωρίς τραυματισμούς.","en":"The 30-year-old skipper of a tourist boat was arrested after a fire sank two vessels off Paxos, causing marine pollution. The 18 US passengers and crews disembarked without injuries.","tel":["Παξοί","σκάφος","φωτιά","ρύπανση"],"ten":["Paxos","boat","fire","pollution"],"s":"negative"},
 "9c434391a5e7": {"i":50,"el":"Αύριο απολογείται ο 65χρονος Ιταλός που κατηγορείται για το διπλό έγκλημα στην Αιγιάλεια, με θύματα τη σύντροφό του και τον γιο της. Έλαβε προθεσμία και εξακολουθεί να αρνείται οποιαδήποτε εμπλοκή.","en":"A 65-year-old Italian charged with the double murder in Aigialeia — his partner and her son — testifies tomorrow. He sought a postponement and continues to deny any involvement.","tel":["Αιγιάλεια","έγκλημα","δικαιοσύνη","ανακριτής"],"ten":["Aigialeia","murder","justice","examining magistrate"],"s":"negative"},
 "d735cfa934ab": {"i":57,"el":"Νέο έκτακτο δελτίο της ΕΜΥ προειδοποιεί για ισχυρές βροχές, καταιγίδες, μπουρίνια και πιθανές χαλαζοπτώσεις σε βόρεια και κεντρική Ελλάδα, καθώς και στη Θράκη και το ΒΑ Αιγαίο.","en":"A new emergency bulletin from the national weather service warns of heavy rain, thunderstorms, squalls and possible hail in northern and central Greece, as well as Thrace and the NE Aegean.","tel":["καιρός","ΕΜΥ","κακοκαιρία","καταιγίδες"],"ten":["weather","forecast","storm","thunderstorms"],"s":"neutral"},
 "db5d115ec705": {"i":44,"el":"Τραγωδία στη Θεσσαλονίκη: 79χρονος έχασε τη ζωή του μετά από πτώση από τον πρώτο όροφο του νοσοκομείου «Παπανικολάου» υπό αδιευκρίνιστες συνθήκες. Την υπόθεση ερευνά η αστυνομία.","en":"Tragedy in Thessaloniki: a 79-year-old died after falling from the first floor of Papanikolaou hospital under unclear circumstances. Police are investigating.","tel":["Θεσσαλονίκη","νοσοκομείο","θάνατος","έρευνα"],"ten":["Thessaloniki","hospital","death","investigation"],"s":"negative"},
 "e65f86d61180": {"i":40,"el":"Σεισμός μεγέθους 3,7 Ρίχτερ σημειώθηκε το πρωί στο Προκόπι Ευβοίας, με εστιακό βάθος 10,8 χλμ. και επίκεντρο 5 χλμ. νοτιοδυτικά του Προκοπίου.","en":"A magnitude 3.7 earthquake struck near Prokopi, Evia, in the morning, at a focal depth of 10.8 km and epicenter 5 km southwest of Prokopi.","tel":["σεισμός","Εύβοια","Προκόπι"],"ten":["earthquake","Evia","Prokopi"],"s":"neutral"},
 "a9359c7ed71a": {"i":46,"el":"Ανήλικο 13 ετών βρέθηκε να κλαίει αβοήθητο σε δρόμο της Τούμπας στη Θεσσαλονίκη. Συνελήφθη η 47χρονη μητέρα του για έκθεση ανηλίκου σε κίνδυνο και το παιδί φιλοξενείται σε συγγενείς.","en":"A 13-year-old was found crying unattended on a street in Toumba, Thessaloniki. The child's 47-year-old mother was arrested for child endangerment, and the child is staying with relatives.","tel":["Θεσσαλονίκη","ανήλικος","σύλληψη","Τούμπα"],"ten":["Thessaloniki","minor","arrest","Toumba"],"s":"negative"},
 "fcdf205e759a": {"i":43,"el":"Σοβαρή συμπλοκή μεταξύ ανηλίκων στην πλατεία Δικαστηρίων στον Πύργο, με τουλάχιστον 20 άτομα παρόντα. Αστυνομικοί προχώρησαν στην προσαγωγή πέντε ανηλίκων.","en":"A serious brawl among minors broke out in the courthouse square in Pyrgos, with at least 20 people present. Police detained five minors.","tel":["Πύργος","συμπλοκή","ανήλικοι","αστυνομία"],"ten":["Pyrgos","brawl","minors","police"],"s":"negative"},
 # ===== WORLD =====
 "2641ae8e9d92": {"i":58,"el":"Ο Βρετανός πρωθυπουργός Κιρ Στάρμερ διόρισε τον Νταν Τζάρβις υπουργό Άμυνας μετά την αιφνιδιαστική παραίτηση του Τζον Χίλι, που αποχώρησε εκφράζοντας διαφωνίες για τις χαμηλές αμυντικές δαπάνες.","en":"UK PM Keir Starmer appointed Dan Jarvis defense secretary after the surprise resignation of John Healey, who left citing disagreements over low defense spending.","tel":["Βρετανία","Στάρμερ","άμυνα","Τζάρβις"],"ten":["UK","Starmer","defense","Jarvis"],"s":"neutral"},
 "71ca860a8846": {"i":64,"el":"Η Ευρωπαϊκή Επιτροπή πρότεινε πακέτο στήριξης 540 εκατ. ευρώ για τους αγρότες της ΕΕ λόγω της εκτίναξης των τιμών των λιπασμάτων, εξαιτίας του πολέμου με το Ιράν. Με εθνικούς πόρους μπορεί να φτάσει το 1,5 δισ.","en":"The European Commission proposed a €540 million support package for EU farmers due to soaring fertilizer prices stemming from the war with Iran. With national funds it could reach €1.5 billion.","tel":["ΕΕ","αγρότες","λιπάσματα","Κομισιόν"],"ten":["EU","farmers","fertilizer","Commission"],"s":"neutral"},
 "e1ecf628110b": {"i":56,"el":"Ανεβαίνει το πολιτικό «θερμόμετρο» στα Τίρανα: ο Αλβανός πρωθυπουργός Έντι Ράμα οργανώνει αντισυγκέντρωση οπαδών απέναντι στις αντικυβερνητικές διαδηλώσεις για την επένδυση στη Σβερνίτσα/Σάσωνα και κατηγορίες διαφθοράς.","en":"Political tensions rise in Tirana: Albanian PM Edi Rama is staging a counter-rally of supporters against anti-government protests over the Svernica/Sazan investment and corruption accusations.","tel":["Αλβανία","Ράμα","διαδηλώσεις","Τίρανα"],"ten":["Albania","Rama","protests","Tirana"],"s":"negative"},
 "985d3addce94": {"i":50,"el":"Συναγερμός στο αεροδρόμιο του Αμβούργου: εκκενώθηκε η περιοχή ελέγχου ασφαλείας και διακόπηκαν απογειώσεις μετά την ενεργοποίηση κομβίου έκτακτης ανάγκης από άνδρα που απέκτησε πρόσβαση σε απαγορευμένη ζώνη.","en":"Security alert at Hamburg airport: the passenger screening area was evacuated and departures halted after a man activated an emergency button to access a restricted zone.","tel":["Αμβούργο","αεροδρόμιο","ασφάλεια","εκκένωση"],"ten":["Hamburg","airport","security","evacuation"],"s":"negative"},
 "d3011ef8c069": {"i":54,"el":"Οι αρχές στη Βόρεια Ιρλανδία παραμένουν σε επιφυλακή μετά από δύο νύχτες ταραχών στο Μπέλφαστ. Η αστυνομία (PSNI) έκανε χρήση πλαστικών σφαιρών και κανονιών νερού· τουλάχιστον 16 συλλήψεις.","en":"Authorities in Northern Ireland remain on alert after two nights of unrest in Belfast. Police (PSNI) used plastic bullets and water cannon; at least 16 people have been arrested.","tel":["Βόρεια Ιρλανδία","Μπέλφαστ","ταραχές","PSNI"],"ten":["Northern Ireland","Belfast","riots","PSNI"],"s":"negative"},
 "25b751fa19d8": {"i":75,"el":"Το Ιράν διαμηνύει ότι η συμφωνία με τις ΗΠΑ δεν έχει οριστικοποιηθεί, παρά τους ισχυρισμούς Τραμπ. Σύμφωνα με το Mehr, απαιτείται έγκριση από τις αρμόδιες αρχές, ενώ το πρόγραμμα βαλλιστικών πυραύλων μένει εκτός ατζέντας.","en":"Iran signals that a deal with the US is not finalized despite Trump's claims. Per Mehr, approval from competent authorities is required, while the ballistic missile program stays off the agenda.","tel":["Ιράν","ΗΠΑ","συμφωνία","Τραμπ"],"ten":["Iran","US","deal","Trump"],"s":"neutral"},
 "d0550a6f3ecc": {"i":52,"el":"Ο Ντόναλντ Τραμπ οργανώνει τουρνουά MMA με αρένα-κλουβί στον νότιο κήπο του Λευκού Οίκου για τα 80ά γενέθλιά του, κόστους 60 εκατ. δολαρίων, προκαλώντας οργή εν μέσω αύξησης του κόστους ζωής.","en":"Donald Trump is staging a $60 million MMA tournament with a caged arena in the White House south lawn for his 80th birthday, sparking anger amid rising living costs.","tel":["Τραμπ","Λευκός Οίκος","MMA","γενέθλια"],"ten":["Trump","White House","MMA","birthday"],"s":"negative"},
 "f4fdbaf3c3c9": {"i":67,"el":"Ο Έλον Μασκ έγινε ο πρώτος τρισεκατομμυριούχος στην ιστορία μετά την IPO-ρεκόρ της SpaceX (75 δισ. δολ.), με τη συνολική του περιουσία να ξεπερνά το 1,1 τρισ. δολάρια.","en":"Elon Musk became history's first trillionaire after SpaceX's record IPO ($75 billion), with his total wealth surpassing $1.1 trillion.","tel":["Μασκ","SpaceX","IPO","τρισεκατομμυριούχος"],"ten":["Musk","SpaceX","IPO","trillionaire"],"s":"neutral"},
 "e137769c78ad": {"i":48,"el":"Λήξη συναγερμού στο αεροδρόμιο του Αμβούργου: τα προληπτικά μέτρα ήρθησαν και οι έλεγχοι ξανάρχισαν, αλλά παραμένουν σημαντικές καθυστερήσεις και ακυρώσεις πτήσεων. Ο δράστης συνελήφθη.","en":"All-clear at Hamburg airport: precautionary measures were lifted and screening resumed, but significant flight delays and cancellations remain. The perpetrator was arrested.","tel":["Αμβούργο","αεροδρόμιο","πτήσεις","καθυστερήσεις"],"ten":["Hamburg","airport","flights","delays"],"s":"neutral"},
 "aaf0c4374b18": {"i":66,"el":"Η Ουκρανία αναμένεται να ζητήσει επιπλέον 20 δισ. δολάρια στρατιωτικής χρηματοδότησης από τους συμμάχους στην «Ομάδα Ραμστάιν», επικαλούμενη «παράθυρο ευκαιρίας» 6-9 μηνών στο πεδίο έναντι της Ρωσίας.","en":"Ukraine is expected to request an additional $20 billion in military funding from allies in the 'Ramstein Group', citing a 6-9 month 'window of opportunity' on the battlefield against Russia.","tel":["Ουκρανία","Ραμστάιν","χρηματοδότηση","Ρωσία"],"ten":["Ukraine","Ramstein","funding","Russia"],"s":"neutral"},
 "f212ac9a2d9f": {"i":63,"el":"Γερμανός κυβερνητικός αξιωματούχος δήλωσε ότι σημειώνεται πρόοδος προς διπλωματική λύση για τον τερματισμό του πολέμου στο Ιράν, στο πλαίσιο εντατικών διπλωματικών διεργασιών για αποκλιμάκωση στη Μέση Ανατολή.","en":"A German government official said progress is being made toward a diplomatic solution to end the war in Iran, amid intensive diplomatic efforts to de-escalate in the Middle East.","tel":["Γερμανία","Ιράν","διπλωματία","Μέση Ανατολή"],"ten":["Germany","Iran","diplomacy","Middle East"],"s":"positive"},
 "a7d4175fdadd": {"i":70,"el":"Το ιρανικό πρακτορείο Mehr δημοσίευσε προσχέδιο 14 σημείων μνημονίου κατανόησης Ιράν-ΗΠΑ, με εκτεταμένες πολιτικές, στρατιωτικές και οικονομικές ρυθμίσεις για άμεση αποκλιμάκωση και διαπραγματεύσεις 60 ημερών. Δεν επιβεβαιώθηκε από την Ουάσιγκτον.","en":"Iran's Mehr agency published a 14-point draft memorandum of understanding with the US, with extensive political, military and economic arrangements for immediate de-escalation and 60-day talks. It was not confirmed by Washington.","tel":["Ιράν","ΗΠΑ","προσχέδιο","διαπραγματεύσεις"],"ten":["Iran","US","draft","negotiations"],"s":"neutral"},
 "099c00709b0b": {"i":60,"el":"Ο πρώην πρόεδρος της Νότιας Κορέας Γιουν Σουκ Γέολ καταδικάστηκε σε 30 χρόνια κάθειρξη για την αποστολή drones στη Βόρεια Κορέα, ως πρόσχημα για να κηρύξει στρατιωτικό νόμο· είχε ήδη καταδικαστεί ισόβια για «εξέγερση».","en":"Former South Korean president Yoon Suk Yeol was sentenced to 30 years for sending drones to North Korea as a pretext to declare martial law; he had already been given life for 'insurrection'.","tel":["Νότια Κορέα","Γιουν","drones","στρατιωτικός νόμος"],"ten":["South Korea","Yoon","drones","martial law"],"s":"negative"},
 "eadffeec3aad": {"i":55,"el":"Ο Πάπας Λέων επισκέφθηκε κέντρο υποδοχής μεταναστών στην Τενερίφη, δηλώνοντας «είμαστε όλοι μετανάστες» και καλώντας τους διακινητές να μετανοήσουν, στο τέλος της περιοδείας του στην Ισπανία.","en":"Pope Leo visited a migrant reception center in Tenerife, declaring 'we are all migrants' and calling on smugglers to repent, at the end of his tour of Spain.","tel":["Πάπας","μετανάστες","Τενερίφη","Ισπανία"],"ten":["Pope","migrants","Tenerife","Spain"],"s":"neutral"},
 # ===== OPINION =====
 "40a990d32126": {"i":50,"el":"Σατιρικό σχόλιο (Στέντωρ) για την προεκλογική αισθητική της πολιτικής επικοινωνίας στα social media, με αφορμή ατάκα του εκπροσώπου του ΠΑΣΟΚ Κ. Τσουκαλά περί δημογραφικού.","en":"A satirical column (Stentor) on the pre-election aesthetics of political communication on social media, prompted by a remark from PASOK spokesman Konstantinos Tsoukalas on the demographic issue.","tel":["σάτιρα","προεκλογικά","social media","ΠΑΣΟΚ"],"ten":["satire","pre-election","social media","PASOK"],"s":"neutral"},
 "54b8f0ed24a6": {"i":57,"el":"Άρθρο γνώμης του Θ. Γεωργακόπουλου που συγκρίνει τις διαμαρτυρίες για τα Μουντιάλ Κατάρ και Ρωσίας με τη σιωπή για το φετινό, θέτοντας ζητήματα υποκρισίας και ρατσισμού της Δύσης.","en":"An opinion piece by Thodoris Georgakopoulos comparing protests over the Qatar and Russia World Cups with the silence around this year's, raising questions of Western hypocrisy and racism.","tel":["Μουντιάλ","ρατσισμός","Δύση","υποκρισία"],"ten":["World Cup","racism","West","hypocrisy"],"s":"neutral"},
 "5eed8519a079": {"i":62,"el":"Άρθρο της Ξ. Κουναλάκη για τα έξι χρόνια του Gov.gr: πίσω από την εντυπωσιακή ψηφιακή πρόσοψη εξακολουθούν να υπάρχουν παλιά προβλήματα δημόσιας διοίκησης. Παραλληλίζει την κατάσταση με ταινία του Λ. Κωνσταντάρα.","en":"An opinion piece by Xenia Kounalaki on Gov.gr's sixth anniversary: behind the impressive digital facade, old public-administration problems persist. She likens it to a Lambros Konstantaras film.","tel":["Gov.gr","ψηφιοποίηση","δημόσια διοίκηση","τεχνολογία"],"ten":["Gov.gr","digitization","public administration","technology"],"s":"neutral"},
 "116536e6f15e": {"i":53,"el":"Δοκίμιο του Τ. Θεοδωρόπουλου με αφορμή την ανακήρυξη από την Τουρκία ως αρχαιολογικού χώρου του πεδίου της μάχης του Γρανικού, που σχολιάζει την οικειοποίηση της ελληνικής/αρχαίας ιστορίας.","en":"An essay by Takis Theodoropoulos prompted by Turkey designating the Granicus battlefield an archaeological site, reflecting on the appropriation of Greek/ancient history.","tel":["Τουρκία","ιστορία","Μ. Αλέξανδρος","πολιτισμός"],"ten":["Turkey","history","Alexander the Great","culture"],"s":"neutral"},
 "7488a12f7d91": {"i":58,"el":"Άρθρο του Π. Μανδραβέλη που παραλληλίζει τις πρόσφατες ταραχές και επιθέσεις σε σπίτια/μαγαζιά στο Μπέλφαστ με τη ναζιστική «Νύχτα των Κρυστάλλων» του 1938.","en":"An article by Paschos Mandravelis drawing a parallel between the recent riots and attacks on homes and shops in Belfast and the Nazi 'Kristallnacht' of 1938.","tel":["Μπέλφαστ","Κρίσταλναχτ","βία","ρατσισμός"],"ten":["Belfast","Kristallnacht","violence","racism"],"s":"negative"},
 "f865532808ff": {"i":59,"el":"Άρθρο του Α. Έλλη για την αδυναμία Γερμανίας-Γαλλίας να συμφωνήσουν στην κοινή ανάπτυξη ευρωπαϊκού μαχητικού 6ης γενιάς, ενώ η Αμερική πιέζει την Ευρώπη να αναλάβει την άμυνά της.","en":"An article by Athanasios Ellis on the German-French failure to agree on jointly developing a 6th-generation European fighter jet, as America pressures Europe to take charge of its own defense.","tel":["άμυνα","Ευρώπη","μαχητικό","Γερμανία-Γαλλία"],"ten":["defense","Europe","fighter jet","Germany-France"],"s":"negative"},
 "18995d8fa73c": {"i":54,"el":"Άρθρο του Σ. Μουμτζή για το ντοκιμαντέρ «Στο χιλιοστό» του ΣΚΑΪ για το πρώτο εξάμηνο του 2015, που φωτίζει τα «ψιλά γράμματα» της κρίσης μέσα από μαρτυρίες πρωταγωνιστών.","en":"An article by Sakis Moumtzis on SKAI's documentary 'Sto Chiliosto' about the first half of 2015, which sheds light on the 'fine print' of the crisis through participants' testimonies.","tel":["ντοκιμαντέρ","2015","κρίση","ΣΥΡΙΖΑ"],"ten":["documentary","2015","crisis","SYRIZA"],"s":"neutral"},
 "ddb5fc55b165": {"i":55,"el":"Άρθρο της Β. Στεργίου για την «ασυδοσία» εταιρειών σε κρίσιμα δίκτυα (ρεύμα, ίντερνετ) και την αίσθηση απώλειας αυτονομίας των καταναλωτών απέναντι στις χρεώσεις και τα ακριβά τιμολόγια.","en":"An article by Vivian Stergiou on the 'impunity' of companies in critical networks (electricity, internet) and consumers' sense of lost autonomy in the face of charges and high tariffs.","tel":["ρεύμα","ίντερνετ","καταναλωτές","τιμολόγια"],"ten":["electricity","internet","consumers","tariffs"],"s":"negative"},
 "29e23bd6e398": {"i":52,"el":"Άρθρο του Μ. Τσιντσίνη για την εμπορευματοποίηση του ποδοσφαίρου υπό τον πρόεδρο της FIFA Τζάνι Ινφαντίνο, με ακριβά εισιτήρια και διοργανώσεις σε «εστίες του νέου αυταρχισμού».","en":"An article by Michalis Tsintsinis on the commercialization of football under FIFA president Gianni Infantino, with expensive tickets and tournaments hosted in 'hubs of the new authoritarianism'.","tel":["FIFA","Ινφαντίνο","ποδόσφαιρο","Μουντιάλ"],"ten":["FIFA","Infantino","football","World Cup"],"s":"negative"},
 "75c2e36d4b44": {"i":60,"el":"Άρθρο του Κ. Ιορδανίδη για τον «εγκλωβισμό» του Ντ. Τραμπ, που έχει ανακοινώσει 37 φορές «κατάπαυση πυρός» στον πόλεμο ΗΠΑ-Ισραήλ εναντίον Ιράν, με τις λέξεις να χάνουν το νόημά τους.","en":"An article by Costas Iordanidis on Trump's 'entrapment', having announced a 'ceasefire' 37 times in the US-Israel war against Iran, as words lose their meaning.","tel":["Τραμπ","Ιράν","κατάπαυση πυρός","γεωπολιτική"],"ten":["Trump","Iran","ceasefire","geopolitics"],"s":"negative"},
 "c7322c264a48": {"i":48,"el":"Ρεπορτάζ-χρονογράφημα της Ν. Δημητρίου για την επιστροφή της κουλτούρας χορού στα μπαρ της Αθήνας, με αφορμή ένα πάρτι στο Burger Disco Club στο Σύνταγμα.","en":"A feature by Nena Dimitriou on the return of dance culture to Athens' bars, prompted by a party at the Burger Disco Club in Syntagma.","tel":["Αθήνα","νυχτερινή ζωή","χορός","μπαρ"],"ten":["Athens","nightlife","dance","bars"],"s":"positive"},
 "702e4f8c8a1e": {"i":56,"el":"Κύριο άρθρο της «Κ» για τον πληθωρισμό: οι «συμφωνίες κυρίων» και οι καλές προθέσεις δεν επαρκούν για τον έλεγχο των τιμών σε μια αγορά με στρεβλώσεις και αδιαφάνεια.","en":"A Kathimerini editorial on inflation: 'gentlemen's agreements' and good intentions are insufficient to control prices in a market beset by distortions and opacity.","tel":["πληθωρισμός","ακρίβεια","αγορά","τιμές"],"ten":["inflation","cost of living","market","prices"],"s":"negative"},
 "a1ba1f154e66": {"i":51,"el":"Άρθρο του Α. Λακασά για την αιφνιδιαστική απαίτηση του υπουργείου Παιδείας να επιλέξουν οι εκπαιδευτικοί τον Ιούνιο τα βιβλία για το 2027-2028, που προκάλεσε άμεσες διαμαρτυρίες συνδικαλιστών και κομμάτων.","en":"An article by Apostolos Lakasas on the education ministry's abrupt demand that teachers choose textbooks for 2027-2028 in June, which sparked immediate protests from unions and parties.","tel":["Παιδεία","πολλαπλό βιβλίο","εκπαιδευτικοί","διαμαρτυρίες"],"ten":["education","multiple textbook","teachers","protests"],"s":"negative"},
 # ===== CULTURE =====
 "70079b6cc7ba": {"i":50,"el":"Γεννιέται στη Σητεία της Κρήτης ένα νέο Λογοτεχνικό Φεστιβάλ, με τέσσερα στρογγυλά τραπέζια όπου είκοσι Έλληνες συγγραφείς θα συζητήσουν για το ιστορικό και αστυνομικό μυθιστόρημα, την αυτοβιογράφηση και την ντοπιολαλιά.","en":"A new Literary Festival is born in Sitia, Crete, with four round tables where twenty Greek authors will discuss historical and crime fiction, autobiography and regional dialect in literature.","tel":["λογοτεχνία","φεστιβάλ","Σητεία","συγγραφείς"],"ten":["literature","festival","Sitia","authors"],"s":"positive"},
 "9dec112bf842": {"i":58,"el":"Ο 27χρονος Ελληνοαλβανός σκηνοθέτης Μάριο Μπανούσι μιλά στην «Κ» λίγο πριν τη βράβευσή του με τον Αργυρό Λέοντα της Μπιενάλε Βενετίας για το θέατρο, βραβείο που πρότεινε ο Γουίλεμ Νταφόε.","en":"The 27-year-old Greek-Albanian director Mario Banushi speaks to Kathimerini shortly before receiving the Silver Lion for theater at the Venice Biennale, an award proposed by Willem Dafoe.","tel":["Μπανούσι","Βενετία","θέατρο","Αργυρός Λέων"],"ten":["Banushi","Venice","theater","Silver Lion"],"s":"positive"},
 "fdf5457952d4": {"i":40,"el":"Η στήλη «Το τραγούδι της ημέρας» παρουσιάζει ένα ζεϊμπέκικο του Χ. Νικολόπουλου, σε στίχους Α. Δαβαράκη, ερμηνευμένο από τη Λίτσα Διαμάντη, μια από τις πιο προικισμένες ερμηνεύτριες του ελληνικού τραγουδιού.","en":"The 'Song of the Day' column features a zeibekiko by Christos Nikolopoulos, with lyrics by Aris Davarakis, performed by Litsa Diamanti, one of Greek song's most gifted performers.","tel":["μουσική","ρεμπέτικο","Λίτσα Διαμάντη","τραγούδι"],"ten":["music","rebetiko","Litsa Diamanti","song"],"s":"positive"},
 "dd439c150fa7": {"i":47,"el":"Με αφορμή το Μουντιάλ 2026, κορυφαία μουσεία της Νέας Υόρκης (Whitney, Guggenheim, Μουσείο Φυσικής Ιστορίας) εξερευνούν τη σχέση του ποδοσφαίρου με την τέχνη, με προβολές αγώνων και μια βίντεο εγκατάσταση για τον Ζιντάν.","en":"Ahead of the 2026 World Cup, top New York museums (Whitney, Guggenheim, Natural History) are exploring football's relationship with art, with match screenings and a video installation on Zidane.","tel":["Μουντιάλ","μουσεία","Νέα Υόρκη","τέχνη"],"ten":["World Cup","museums","New York","art"],"s":"positive"},
 "86600bbbe7bb": {"i":49,"el":"Ο Στίβεν Σπίλμπεργκ αποκάλυψε ότι ζήτησε επανειλημμένα να σκηνοθετήσει ταινία Τζέιμς Μποντ μετά τα «Σαγόνια του Καρχαρία», αλλά ο παραγωγός Άλμπερτ Μπρόκολι τον απέρριψε.","en":"Steven Spielberg revealed he repeatedly asked to direct a James Bond film after 'Jaws', but producer Albert Broccoli turned him down.","tel":["Σπίλμπεργκ","Τζέιμς Μποντ","σινεμά","Χόλιγουντ"],"ten":["Spielberg","James Bond","cinema","Hollywood"],"s":"neutral"},
 "a82504dd0252": {"i":45,"el":"Ο γιος του Κλιντ Ιστγουντ, Σκοτ, διαψεύδει τις φήμες περί συνταξιοδότησης του 96χρονου πατέρα του από το σινεμά, λέγοντας ότι δεν έχει ακούσει κάτι τέτοιο από τον ίδιο.","en":"Clint Eastwood's son Scott denies rumors that his 96-year-old father has retired from filmmaking, saying he hasn't heard any such thing from him directly.","tel":["Ιστγουντ","σινεμά","φήμες","Χόλιγουντ"],"ten":["Eastwood","cinema","rumors","Hollywood"],"s":"neutral"},
 "49d8ab6a4d07": {"i":52,"el":"Το θρυλικό σινεμά «Μπρόντγουαιη» στην Πατησίων ξαναγεννιέται ως σύγχρονη θεατρική αίθουσα 800 θέσεων («Αθενς Μπρόντγουαιη»), που θα ανοίξει τον Δεκέμβριο του 2026 από τις Θεατρικές Επιχειρήσεις Τάγαρη.","en":"The legendary 'Broadway' cinema on Patision Street is being reborn as a modern 800-seat theater ('Athens Broadway'), opening in December 2026 under Tagaris Theatrical Enterprises.","tel":["Μπρόντγουαιη","θέατρο","Πατησίων","Αθήνα"],"ten":["Broadway","theater","Patision","Athens"],"s":"positive"},
 "283b87ba4103": {"i":48,"el":"Το Athens Photo Festival εστιάζει στη γονεϊκότητα, την ταυτότητα και τις ρίζες, με έργα όπως το «Our Hidden Room» του Αιγύπτιου Μοχάμεντ Χασάν για τη σχέση με τον διπολικό πατέρα του.","en":"The Athens Photo Festival focuses on parenthood, identity and roots, with works such as 'Our Hidden Room' by Egyptian artist Mohamed Hassan about his relationship with his bipolar father.","tel":["φωτογραφία","φεστιβάλ","Αθήνα","ταυτότητα"],"ten":["photography","festival","Athens","identity"],"s":"neutral"},
 "663a4a78b319": {"i":42,"el":"Φιλανθρωπικό μπαζάρ από τους «Φίλους της Μέριμνας» από τις 18-21 Ιουνίου στο Σεράφειο, με ποιοτικά ενδύματα και αξεσουάρ· τα έσοδα στηρίζουν την ανακουφιστική φροντίδα παιδιών.","en":"A charity bazaar by the 'Friends of Merimna' runs June 18-21 at the Serafeio, with quality clothing and accessories; proceeds support palliative care for children.","tel":["μπαζάρ","φιλανθρωπία","Μέριμνα","Αθήνα"],"ten":["bazaar","charity","Merimna","Athens"],"s":"positive"},
 "0049403c63ba": {"i":44,"el":"Πολιτιστικός οδηγός για το Σαββατοκύριακο: διασκευή της «Λυσιστράτης» από τον Στ. Κραουνάκη στο Ηρώδειο, «Τα ημερολόγια του Σοπέν» στο Ωδείο Αθηνών και συναυλίες ambient στη Θεσσαλονίκη.","en":"A weekend culture guide: Stamatis Kraounakis's adaptation of 'Lysistrata' at the Herodion, 'Chopin's Diaries' at the Athens Conservatory, and ambient concerts in Thessaloniki.","tel":["εκδηλώσεις","θέατρο","συναυλίες","Αθήνα"],"ten":["events","theater","concerts","Athens"],"s":"positive"},
 "be448afb8b41": {"i":43,"el":"Διαπολιτισμική εκδήλωση Ελλάδας-Κίνας στο Μουσείο Μαραθωνίου Δρόμου, με κοινή ερμηνεία της «Ωδής στην Αφροδίτη» της Σαπφούς και έργου του Σου Σι, για την ενίσχυση της πολιτιστικής συνεργασίας.","en":"A Greek-Chinese intercultural event at the Marathon Run Museum, featuring a joint performance of Sappho's 'Ode to Aphrodite' and a work by Su Shi, to strengthen cultural cooperation.","tel":["Ελλάδα-Κίνα","πολιτισμός","Μαραθώνας","Σαπφώ"],"ten":["Greece-China","culture","Marathon","Sappho"],"s":"positive"},
 "48afc221a5c0": {"i":62,"el":"Πέθανε σε ηλικία 88 ετών ο σπουδαίος Βρετανός καλλιτέχνης Ντέιβιντ Χόκνεϊ, μία από τις επιδραστικότερες μορφές της σύγχρονης τέχνης του 20ού και 21ου αιώνα, γνωστός για τις εμβληματικές πισίνες του.","en":"Renowned British artist David Hockney has died at age 88, one of the most influential figures of 20th- and 21st-century modern art, known for his iconic swimming-pool paintings.","tel":["Χόκνεϊ","τέχνη","θάνατος","ζωγραφική"],"ten":["Hockney","art","death","painting"],"s":"negative"},
 "cbf85dae9043": {"i":45,"el":"Ιδρύθηκε στο Παρίσι η SAPJH, νεοσύστατη ακαδημαϊκή και επαγγελματική ένωση από 11 νέους Έλληνες, για τη δικτύωση και στήριξη των πάνω από 2.500 Ελλήνων που σπουδάζουν και εργάζονται στη Γαλλία.","en":"SAPJH, a new academic and professional association founded in Paris by 11 young Greeks, has been set up to network and support the over 2,500 Greeks studying and working in France.","tel":["διασπορά","Γαλλία","νέοι","SAPJH"],"ten":["diaspora","France","youth","SAPJH"],"s":"positive"},
}

# Per-category themes (curated from the day's stories)
THEMES = {
 "politics": {"el":["Σκάνδαλο πολεοδομιών","Προεκλογικό κλίμα & ΣΥΡΙΖΑ","Ενέργεια & East Med","Ελληνοτουρκικά"],
              "en":["Urban-planning scandal","Pre-election climate & SYRIZA","Energy & East Med","Greek-Turkish relations"]},
 "economy": {"el":["Συντάξεις & ανισότητες","Πληθωρισμός & ακρίβεια","Τράπεζες & επιτόκια","Ακίνητα & επενδύσεις"],
             "en":["Pensions & inequality","Inflation & cost of living","Banks & interest rates","Real estate & investment"]},
 "society": {"el":["Κακοκαιρία & πυρκαγιές","Ανήλικοι σε κίνδυνο","Εγκληματικότητα & ναρκωτικά","Διαφθορά στην υγεία"],
             "en":["Storms & wildfires","Minors at risk","Crime & drugs","Health-sector corruption"]},
 "world": {"el":["Πόλεμος στο Ιράν & διπλωματία","Ουκρανία & άμυνα","Αναταραχές στην Ευρώπη","ΗΠΑ & Τραμπ"],
           "en":["Iran war & diplomacy","Ukraine & defense","European unrest","US & Trump"]},
 "opinion": {"el":["Πληθωρισμός & αγορά","Γεωπολιτική & Τραμπ","Μουντιάλ & κοινωνία","Ψηφιοποίηση & κράτος"],
             "en":["Inflation & the market","Geopolitics & Trump","World Cup & society","Digitization & the state"]},
 "culture": {"el":["Θέατρο & βραβεύσεις","Φεστιβάλ & εκθέσεις","Σινεμά","Πολιτιστική κληρονομιά"],
             "en":["Theater & awards","Festivals & exhibitions","Cinema","Cultural heritage"]},
}

CATS = ["politics","economy","society","world","opinion","culture"]
NOW = datetime.now(timezone.utc).isoformat()

raw = json.load(open(RAW))
by_id = {a["id"]: a for a in raw}

def build_item(a):
    an = A.get(a["id"])
    if not an:
        return None
    cat = a["category_hint"]
    return {
        "id": a["id"],
        "title": a["title"],
        "url": a["url"],
        "author": a.get("author") or "Newsroom",
        "published": a.get("published"),
        "source": "Kathimerini",
        "source_type": "scrape",
        "category": cat,
        "importance": an["i"],
        "content": (a.get("content") or "")[:2000],
        "summary": {"el": an["el"], "en": an["en"]},
        "tags": {"el": an["tel"], "en": an["ten"]},
        "sentiment": an["s"],
    }

cat_items = {c: [] for c in CATS}
for a in raw:
    it = build_item(a)
    if it:
        cat_items[it["category"]].append(it)

missing = [a["id"] for a in raw if a["id"] not in A]
if missing:
    print("WARNING missing analysis for:", missing, file=sys.stderr)

for c in CATS:
    cat_items[c].sort(key=lambda x: x["importance"], reverse=True)
    doc = {
        "date": DATE, "generated_at": NOW, "category": c,
        "item_count": len(cat_items[c]),
        "themes": THEMES[c],
        "items": cat_items[c],
    }
    json.dump(doc, open(OUT / f"{c}.json", "w"), ensure_ascii=False, indent=2)

def flat(it):
    return {"id":it["id"],"title":it["title"],"url":it["url"],"source":it["source"],
            "published":it["published"],"importance":it["importance"],
            "summary":it["summary"],"tags":it["tags"],"sentiment":it["sentiment"]}

categories = {}
for c in CATS:
    categories[c] = {"item_count": len(cat_items[c]),
                     "top_items": [flat(x) for x in cat_items[c][:5]]}

total = sum(len(cat_items[c]) for c in CATS)

exec_el = (
 "Η ειδησεογραφία της ημέρας κυριαρχείται από το προεκλογικό κλίμα και τις πολιτικές κόντρες: "
 "το Μαξίμου αποκρούει τις κατηγορίες για «γαλάζιο» σκάνδαλο στις πολεοδομίες μετά τις παραιτήσεις δύο γενικών γραμματέων, "
 "ο ΣΥΡΙΖΑ κινείται «σε τεντωμένο σχοινί» γύρω από τη συμπόρευση με τον Αλέξη Τσίπρα, ενώ ο πρωθυπουργός τοποθέτησε τις εκλογές στην άνοιξη του 2027. "
 "Στο μέτωπο της εξωτερικής πολιτικής και ενέργειας, η ίδρυση του East Med Energy Center στο Χιούστον σφραγίζει τη συνεργασία Ελλάδας-Κύπρου-Ισραήλ-ΗΠΑ, "
 "με την Τουρκία να εντείνει την πίεση κατά της Λευκωσίας.\n\n"
 "Στην οικονομία, ξεχωρίζουν οι διευρυνόμενες ανισότητες στο συνταξιοδοτικό, οι επιπτώσεις της αύξησης επιτοκίων της ΕΚΤ στις τράπεζες και η συνεχιζόμενη πίεση από την ακρίβεια. "
 "Διεθνώς, η προσοχή στρέφεται στον πόλεμο στο Ιράν, με ιρανικό προσχέδιο 14 σημείων προς τις ΗΠΑ και ενδείξεις διπλωματικής προόδου, καθώς και στο νέο αίτημα της Ουκρανίας για 20 δισ. δολάρια. "
 "Στην κοινωνία, η κακοκαιρία και ο κίνδυνος πυρκαγιών συνυπάρχουν με υποθέσεις προστασίας ανηλίκων και διαφθοράς στην υγεία.\n\n"
 "Στον πολιτισμό, η ημέρα σημαδεύτηκε από τον θάνατο του Ντέιβιντ Χόκνεϊ και τη βράβευση του Μάριο Μπανούσι στη Βενετία, ενώ τα άρθρα γνώμης επικεντρώθηκαν στον πληθωρισμό, τη γεωπολιτική του Τραμπ και την κριτική στο Μουντιάλ."
)
exec_en = (
 "The day's news is dominated by the pre-election climate and political clashes: the government is rebutting accusations of a New Democracy urban-planning scandal "
 "after two general secretaries resigned, SYRIZA is 'walking a tightrope' over aligning with Alexis Tsipras, and the PM signaled elections for spring 2027. "
 "On foreign policy and energy, the founding of the East Med Energy Center in Houston cements Greece-Cyprus-Israel-US cooperation, while Turkey escalates pressure on Nicosia.\n\n"
 "In the economy, widening pension inequalities, the impact of the ECB rate hike on banks, and persistent inflationary pressure stand out. "
 "Internationally, attention turns to the war in Iran — with a 14-point Iranian draft to the US and signs of diplomatic progress — and Ukraine's new $20 billion funding request. "
 "Domestically, bad weather and wildfire risk coincide with cases of child protection and health-sector corruption.\n\n"
 "In culture, the day was marked by the death of David Hockney and Mario Banushi's award in Venice, while opinion pieces focused on inflation, Trump's geopolitics and criticism of the World Cup."
)

top_topics = [
 {"name":{"el":"Σκάνδαλο πολεοδομιών & προεκλογική κόντρα","en":"Urban-planning scandal & pre-election clash"},
  "description":{"el":"Το Μαξίμου αποκρούει τις κατηγορίες περί «γαλάζιου» σκανδάλου μετά τις παραιτήσεις δύο γενικών γραμματέων, εν μέσω έντονης αντιπαράθεσης με την αντιπολίτευση και προεκλογικού κλίματος.","en":"The government rebuts accusations of a New Democracy scandal after two general secretaries resigned, amid sharp opposition confrontation and a pre-election climate."},
  "related_items":["3d9253aaee43","a37d14258390","ba47aa375880","9d930d99de1b","2f9ec70245d3"],"importance":75},
 {"name":{"el":"Πόλεμος στο Ιράν & διπλωματικές διεργασίες","en":"Iran war & diplomatic efforts"},
  "description":{"el":"Ιρανικό προσχέδιο 14 σημείων προς τις ΗΠΑ, ενδείξεις διπλωματικής προόδου κατά τη Γερμανία, αλλά και επιφυλάξεις της Τεχεράνης για οριστικοποίηση της συμφωνίας.","en":"A 14-point Iranian draft to the US, signs of diplomatic progress per Germany, and Tehran's reservations about finalizing any deal."},
  "related_items":["a7d4175fdadd","25b751fa19d8","f212ac9a2d9f","75c2e36d4b44","71ca860a8846"],"importance":74},
 {"name":{"el":"Ενεργειακή συνεργασία στην Αν. Μεσόγειο","en":"East Med energy cooperation"},
  "description":{"el":"Η ίδρυση του East Med Energy Center στο Χιούστον στο πλαίσιο του σχήματος 3+1 ενισχύει τη συνεργασία Ελλάδας-Κύπρου-Ισραήλ-ΗΠΑ, εν μέσω τουρκικής πίεσης.","en":"The founding of the East Med Energy Center in Houston under the 3+1 scheme strengthens Greece-Cyprus-Israel-US cooperation, amid Turkish pressure."},
  "related_items":["7faa9ecee5f0","ffb7aa0ab1d7","364f334857d0"],"importance":72},
 {"name":{"el":"Οικονομικές πιέσεις: συντάξεις, επιτόκια, ακρίβεια","en":"Economic pressures: pensions, rates, inflation"},
  "description":{"el":"Διευρύνεται το χάσμα στις συντάξεις, η αύξηση επιτοκίων της ΕΚΤ ενισχύει τις τράπεζες, ενώ η ακρίβεια και τα κρατικά χρέη παραμένουν στο επίκεντρο.","en":"The pension gap widens, the ECB rate hike boosts banks, while inflation and state arrears remain in focus."},
  "related_items":["9a89e2656ad1","52f936019a2f","335cc6ab1c1c","e32dbe6726ae","702e4f8c8a1e"],"importance":70},
]

summary = {
    "date": DATE, "generated_at": NOW,
    "source_note": f"Articles scraped from kathimerini.gr. {total} articles over 24h.",
    "executive_summary": {"el": exec_el, "en": exec_en},
    "top_topics": top_topics,
    "article_count": total,
    "categories": categories,
    "stats": {"total": total},
}
json.dump(summary, open(OUT / "summary.json", "w"), ensure_ascii=False, indent=2)

print("OK total=%d per-cat=%s" % (total, {c: len(cat_items[c]) for c in CATS}))
